#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	md="mkdir -pv" \
	yt="youtube-dl --geo-bypass-country ru --add-metadata -i -o '/home/nico/dox/vids/%(uploader)s-%(title)s-%(id)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	la="ls -ahN --color=auto --group-directories-first" \
	ll="ls -lhN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -P now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	pm="pulsemixer" \
	tox="toxic -df ~/dox/tox/profs/nico.tox" \


	#tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
alias \
	sdc="shutdown -c" \
	myip="echo 'PUBLIC ip:' && curl -s https://checkip.amazonaws.com" \
